### ISSUE TITLE
Bill of Materials and set up questions

### ISSUE THREAD

**Issue by mdluffy1234** [andyj1/kinect#2]
You wrote in your documentation about the parts you need to get it set up, but you don't have a diagram on how to connect all of the USB cables together to the hub, and to the PC. It is incredibly helpful that you had a diagram for setting up the audio jacks. But without an exact number of separate parts you need, there's no way for a prospective game developer like myself to budget all of the necessary parts. From my personal understanding, assuming you would use a 3 Kinect setup, you would need: 3 Azure Kinects, 2 AUX Cords, 3 USB 3.0 Extension Cables, and 1 USB Hub. But that bill of materials does not account for powering the cables or the Kinects (if they require their own bespoke plugs).

**Comment by andyj1** [comment]
Hi, it was assumed that the set up of this system is actually quite self-explanatory, given that the user has some experience working with the Kinects (Azure DK). What you understood is correct: for 3 devices, each set of power and usb c connecting cables, along with 2 audio cables to connect with one another in this setup.
